import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import Link from "next/link";
import "~/styles/globals.css";
import { AuthGate } from "~/components/auth-gate";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-space-grotesk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${spaceGrotesk.variable} antialiased dark`}>
        <AuthGate>
          <header className="fixed z-50 w-full bg-background p-4 border-b">
            <Link className="text-4xl font-bold" href="/">
              +_+ Creator Daddy
            </Link>
          </header>
          {children}
        </AuthGate>
      </body>
    </html>
  );
}
